### ISSUE TITLE
The Makefile doesn't work in linux

### ISSUE THREAD

**Issue by wbhu** [remidebord/Serial#1]
I have found that when I make the project, it post some errors,like this:
(.text+0x20)：对‘main’未定义的引用
obj/main.o:main.cpp:(.text+0x17)：对‘___main’未定义的引用
obj/main.o:main.cpp:(.text+0xb0)：对‘_printf’未定义的引用
obj/main.o:main.cpp:(.text+0xcc)：对‘_putchar’未定义的引用
obj/main.o:main.cpp:(.text+0xf6)：对‘__Unwind_Resume’未定义的引用
obj/serial.o:serial.cpp:(.text+0x35)：对‘_strcpy’未定义的引用
obj/serial.o:serial.cpp:(.text+0x88)：对‘_CreateFileA@28’未定义的引用
obj/serial.o:serial.cpp:(.text+0xb8)：对‘_printf’未定义的引用
obj/serial.o:serial.cpp:(.text+0xdf)：对‘_SetupComm@12’未定义的引用
obj/serial.o:serial.cpp:(.text+0x2af)：对‘_SetCommTimeouts@8’未定义的引用
obj/serial.o:serial.cpp:(.text+0x2d3)：对‘_SetCommState@8’未定义的引用
obj/serial.o:serial.cpp:(.text+0x2fa)：对‘_printf’未定义的引用
obj/serial.o:serial.cpp:(.text+0x30a)：对‘_CloseHandle@4’未定义的引用
obj/serial.o:serial.cpp:(.text+0x329)：对‘_PurgeComm@8’未定义的引用
obj/serial.o:serial.cpp:(.text+0x366)：对‘_printf’未定义的引用
obj/serial.o:serial.cpp:(.text+0x372)：对‘__Unwind_Resume’未定义的引用
obj/serial.o:serial.cpp:(.text+0x392)：对‘_CloseHandle@4’未定义的引用
obj/serial.o:serial.cpp:(.text+0x3d3)：对‘_WriteFile@20’未定义的引用
obj/serial.o:serial.cpp:(.text+0x41a)：对‘__Unwind_Resume’未定义的引用
obj/serial.o:serial.cpp:(.text+0x476)：对‘_ReadFile@20’未定义的引用
obj/serial.o:serial.cpp:(.text+0x49c)：对‘__Unwind_Resume’未定义的引用
obj/timeout.o:timeout.cpp:(.text+0x28)：对‘_clock’未定义的引用
obj/timeout.o:timeout.cpp:(.text+0x4e)：对‘_clock’未定义的引用
/usr/bin/ld: Serial(.eh_frame): relocation "___gxx_personality_v0+0x0 (type dir32)" goes out of range
/usr/bin/ld: 最终连接失败: 无效的操作
collect2: error: ld returned 1 exit status
make: **\* [Serial] 错误 1
cris@cris:~/gitRep/Serial$ subl Makefile
cris@cris:~/gitRep/Serial$ ls -al

The machine systerm is ubuntu 14.04.

**Comment by remidebord** [comment]
I test it with gcc 4.8.4 and Ubuntu 14.04.

Can you please remove these files (Makefile.win, Serial, Serial.dev and Serial.layout) and then retry.

If the problem is still here, can you add these lines in the serial.h,  just after `#include <stdint.h>`

```
#ifdef __WIN32__
#undef __WIN32__
#endif

#ifdef __CYGWIN__
#undef __CYGWIN__
#endif
```

**Comment by wbhu** [comment]
Thank you. I have solve this problem. I remove the files in the "OBJ"folder and compiled again, and it works. I think we should add the "*.o" files in the ".gitignore".
